# Generated by Django 5.2.17 on 2026-08-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True, verbose_name='پلاک')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'ماشین'), ('MOTORCYCLE', 'موتورسیکلت'), ('BICYCLE', 'دوچرخه')], default='CAR', max_length=20, verbose_name='نوع وسیله نقلیه')),
                ('sub_type', models.CharField(choices=[('PASSENGER', 'عادی / سواری'), ('CARGO', 'باری'), ('ELECTRIC', 'برقی'), ('DISABLED', 'معلولین')], default='PASSENGER', max_length=20, verbose_name='نوع سوخت / حالت')),
                ('color', models.CharField(choices=[('RED', 'قرمز'), ('BLUE', 'آبی'), ('GREEN', 'سبز'), ('BLACK', 'مشکی'), ('WHITE', 'سفید'), ('YELLOW', 'زرد'), ('ORANGE', 'نارنجی'), ('PURPLE', 'بنفش'), ('BROWN', 'قهوه\u200cای'), ('GRAY', 'خاکستری')], default='BLACK', max_length=20, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'وسیله نقلیه',
                'verbose_name_plural': 'وسایل نقلیه',
                'ordering': ['-id'],
            },
        ),
    ]
