# Generated by Django 5.2.17 on 2026-08-27 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا (UUID)')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='کد یکتا جایگاه')),
                ('zone', models.CharField(choices=[('NORTH', 'بخش شمالی'), ('SOUTH', 'بخش جنوبی'), ('WEST', 'بخش غربی'), ('EAST', 'بخش شرقی')], default='NORTH', max_length=50, verbose_name='ناحیه')),
                ('floor', models.CharField(choices=[('GROUND', 'همکف'), ('FLOOR_1', 'طبقه ۱'), ('FLOOR_2', 'طبقه ۲'), ('BASEMENT_1', 'طبقه منفی ۱'), ('BASEMENT_2', 'طبقه منفی ۲')], default='GROUND', max_length=50, verbose_name='طبقه')),
                ('space_type', models.CharField(choices=[('NORMAL', 'عادی'), ('GUEST', 'مهمان'), ('MANAGERS', 'مدیران'), ('DISABLED', 'معلولین'), ('MOTORCYCLE', 'موتور'), ('ELECTRIC', 'خودرو برقی'), ('LOADING', 'بارگیری کوتاه مدت'), ('EMERGENCY', 'جایگاه رزرو اضطراری')], default='NORMAL', max_length=30, verbose_name='نوع جایگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن')),
                ('requires_permission', models.BooleanField(default=False, verbose_name='نیاز به تایید مدیر / مجوز')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ویژگی\u200cها و توضیحات')),
            ],
            options={
                'verbose_name': 'جایگاه پارکینگ',
                'verbose_name_plural': 'جایگاه\u200cهای پارکینگ',
            },
        ),
    ]
