# Generated by Django 5.2.17 on 2026-08-28 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='ساعت شروع')),
                ('end_time', models.DateTimeField(verbose_name='ساعت پایان')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('CANCELED', 'لغو شده '), ('EXPIRED', 'منقضی شده'), ('IN_USE', 'در حال استفاده'), ('COMPLETED', 'تکمیل شده'), ('NEEDS_REVIEW', 'نیازمند بررسی دستی')], default='PENDING', max_length=20, verbose_name='وضعیت درخواست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('is_guest', models.BooleanField(default=False, verbose_name='درخواست مهمان')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مهمان')),
                ('guest_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='ایمیل مهمان')),
                ('guest_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس مهمان')),
                ('guest_plate_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره پلاک مهمان')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل مراجعه')),
                ('parking_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkings.parkingspace', verbose_name='جایگاه ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle', verbose_name='وسیله نقلیه')),
            ],
            options={
                'verbose_name': 'درخواست پارکینگ',
                'verbose_name_plural': 'درخواست\u200cهای پارکینگ',
                'ordering': ['-id'],
            },
        ),
    ]
