# Generated by Django 5.2.17 on 2026-08-29 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_parkingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpaceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع مسدودی')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان مسدودی')),
                ('reason', models.CharField(choices=[('REPAIR', 'تعمیرات و نگهداری'), ('EVENT', 'رویداد سازمانی'), ('CLEANING', 'نظافت و شستشوی محوطه'), ('VIP_RESERVE', 'رزرو مقامات یا مهمان ویژه'), ('EQUIPMENT_FAILURE', 'خرابی تجهیزات'), ('OTHER', 'سایر موارد')], default='REPAIR', max_length=255, verbose_name='دلیل مسدودی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='parkings.parkingspace', verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'انسداد جایگاه',
                'verbose_name_plural': 'انسداد جایگاه ها',
                'ordering': ['-id'],
            },
        ),
    ]
