# Generated by Django 5.2.17 on 2026-08-29 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_parkingspaceblock'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name=' زمان ورود')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نگهبان')),
                ('parking_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkings.parkingrequest', verbose_name='درخواست')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='وسیله نقلیه')),
            ],
            options={
                'verbose_name': ' گزارش ورود و خروج',
                'verbose_name_plural': 'گزارشات ورود و خروج',
            },
        ),
    ]
