# Generated by Django 5.2.17 on 2026-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_entryexitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد درخواست'),
        ),
    ]
