# Generated by Django 5.2.17 on 2026-09-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_alter_parkingrequest_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingrequest',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_requests', to='parkings.parkingspace', verbose_name='جایگاه'),
        ),
    ]
